### ISSUE TITLE
YoutubeClient.search: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by madeyoga** [Shiroechi/YouTubeSearchApi-Java#6]
```java
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at YouTubeSearchApi.YoutubeClient.search(YoutubeClient.java:43)
```

**Comment by madeyoga** [comment]
#7
